---
# Установка MySQL и создание базы данных и пользователя

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: ''
    name: root
    host_all: yes
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes

- name: Create WordPress database
  mysql_db:
    name: "{{ wordpress_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create WordPress MySQL user
  mysql_user:
    name: "{{ wordpress_user }}"
    password: "{{ wordpress_password }}"
    priv: "{{ wordpress_user }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}" 
